/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class MikMod_Drivers_Native_0005fDriver */
/* SYMBOL: "MikMod_Drivers_Native_0005fDriver/sysCheckAccess()I", Java_MikMod_Drivers_Native_0005fDriver_sysCheckAccess_stub */
stack_item *Java_MikMod_Drivers_Native_0005fDriver_sysCheckAccess_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long MikMod_Drivers_Native_0005fDriver_sysCheckAccess(void *);
	_P_[0].i = MikMod_Drivers_Native_0005fDriver_sysCheckAccess(_P_[0].p);
	return _P_ + 1;
}
/* SYMBOL: "MikMod_Drivers_Native_0005fDriver/sysOpenSound(IIIILjava/lang/String;)I", Java_MikMod_Drivers_Native_0005fDriver_sysOpenSound_stub */
stack_item *Java_MikMod_Drivers_Native_0005fDriver_sysOpenSound_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long MikMod_Drivers_Native_0005fDriver_sysOpenSound(void *,long,long,long,long,void *);
	_P_[0].i = MikMod_Drivers_Native_0005fDriver_sysOpenSound(_P_[0].p,((_P_[1].i)),((_P_[2].i)),((_P_[3].i)),((_P_[4].i)),((_P_[5].p)));
	return _P_ + 1;
}
/* SYMBOL: "MikMod_Drivers_Native_0005fDriver/sysCloseSound(I)I", Java_MikMod_Drivers_Native_0005fDriver_sysCloseSound_stub */
stack_item *Java_MikMod_Drivers_Native_0005fDriver_sysCloseSound_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long MikMod_Drivers_Native_0005fDriver_sysCloseSound(void *,long);
	_P_[0].i = MikMod_Drivers_Native_0005fDriver_sysCloseSound(_P_[0].p,((_P_[1].i)));
	return _P_ + 1;
}
/* SYMBOL: "MikMod_Drivers_Native_0005fDriver/sysWriteBuffer(I[BI)I", Java_MikMod_Drivers_Native_0005fDriver_sysWriteBuffer_stub */
stack_item *Java_MikMod_Drivers_Native_0005fDriver_sysWriteBuffer_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long MikMod_Drivers_Native_0005fDriver_sysWriteBuffer(void *,long,void *,long);
	_P_[0].i = MikMod_Drivers_Native_0005fDriver_sysWriteBuffer(_P_[0].p,((_P_[1].i)),((_P_[2].p)),((_P_[3].i)));
	return _P_ + 1;
}
